export const MARKET_ORDER_STATUSES = [
  'SECURITY_TRADING_STATUS_NORMAL_TRADING',
  'SECURITY_TRADING_STATUS_DARK_POOL_AUCTION',
  'SECURITY_TRADING_STATUS_DEALER_NORMAL_TRADING',
  'SECURITY_TRADING_STATUS_BREAK_IN_TRADING'
];

export const LIMIT_ORDER_STATUSES = [
  'SECURITY_TRADING_STATUS_OPENING_PERIOD',
  'SECURITY_TRADING_STATUS_CLOSING_PERIOD',
  'SECURITY_TRADING_STATUS_NORMAL_TRADING',
  'SECURITY_TRADING_STATUS_CLOSING_AUCTION',
  'SECURITY_TRADING_STATUS_DISCRETE_AUCTION',
  'SECURITY_TRADING_STATUS_OPENING_AUCTION_PERIOD',
  'SECURITY_TRADING_STATUS_TRADING_AT_CLOSING_AUCTION_PRICE',
  'SECURITY_TRADING_STATUS_SESSION_ASSIGNED',
  'SECURITY_TRADING_STATUS_SESSION_CLOSE',
  'SECURITY_TRADING_STATUS_SESSION_OPEN',
];
